services:
  proof-server:
    image: midnightntwrk/proof-server:8.1.0@sha256:801bbc0340e9e96f16735f77b523f23c7459e3359842f7c79c2c53f4e994d531
    command: ['midnight-proof-server', '-v']
    container_name: "proof-server_$TESTCONTAINERS_UID"
    ports:
      - '6300'

  indexer:
    image: 'midnightntwrk/indexer-standalone:4.3.2@sha256:a769f7f2eaf34ba7ecaea19e878112d9a4686c5aa9a1d3dce86a42086a9a6444'
    container_name: 'indexer_$TESTCONTAINERS_UID'
    ports:
      - '8088'
    environment:
      RUST_LOG: "indexer=info,chain_indexer=info,indexer_api=info,wallet_indexer=info,indexer_common=info,fastrace_opentelemetry=info,info"
      # Random 32-byte hex-encoded secret used to make the standalone indexer run.
      # Only needed to satisfy the config schema – not meant for secure use.
      APP__INFRA__SECRET: "303132333435363738393031323334353637383930313233343536373839303132"
      APP__INFRA__NODE__URL: "ws://node:9944"
    depends_on:
      node:
        condition: service_started
  node:
    image: 'midnightntwrk/midnight-node:0.22.5@sha256:c65b8b80def751580c190ac2e9402fddfcda04bdfb5a6ec83c5cc42bea154dac'
    container_name: 'node_$TESTCONTAINERS_UID'
    ports:
      - "9944"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      CFG_PRESET: "dev"
      SIDECHAIN_BLOCK_BENEFICIARY: '04bcf7ad3be7a5c790460be82a713af570f22e0f801f6659ab8e84a52be6969e'
